scanner:
  timeout: 5
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  max_retries: 3
  
output:
  directory: "output"
  save_results: true
  log_level: "INFO"

wordlists:
  directory: "wordlists"
  default: "common" 